/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
        "tertiary-fixed-dim": "#c6c6c6",
        "on-error-container": "#ffdad6",
        "on-tertiary-container": "#ececec",
        "secondary-fixed": "#e2e2e2",
        "primary-fixed-dim": "#b1c5ff",
        "on-surface-variant": "#c3c6d5",
        "background": "#131313",
        "on-error": "#690005",
        "secondary": "#c6c6c7",
        "inverse-surface": "#e5e2e1",
        "surface-variant": "#353534",
        "surface-container-lowest": "#0e0e0e",
        "surface": "#131313",
        "on-tertiary": "#2f3131",
        "secondary-fixed-dim": "#c6c6c7",
        "on-secondary-container": "#b4b5b5",
        "on-secondary-fixed-variant": "#454747",
        "on-primary": "#002c70",
        "primary-container": "#3366cc",
        "outline-variant": "#434653",
        "on-primary-container": "#e7ebff",
        "inverse-primary": "#2259bf",
        "tertiary-fixed": "#e2e2e2",
        "on-surface": "#e5e2e1",
        "on-background": "#e5e2e1",
        "on-secondary-fixed": "#1a1c1c",
        "surface-container": "#201f1f",
        "error-container": "#93000a",
        "on-tertiary-fixed-variant": "#454747",
        "on-tertiary-fixed": "#1a1c1c",
        "tertiary-container": "#6a6b6b",
        "secondary-container": "#454747",
        "on-secondary": "#2f3131",
        "surface-dim": "#131313",
        "primary": "#b1c5ff",
        "surface-container-high": "#2a2a2a",
        "on-primary-fixed": "#001946",
        "surface-container-low": "#1c1b1b",
        "surface-tint": "#b1c5ff",
        "surface-bright": "#3a3939",
        "on-primary-fixed-variant": "#00419d",
        "tertiary": "#c6c6c6",
        "outline": "#8d909e",
        "surface-container-highest": "#353534",
        "error": "#ffb4ab",
        "primary-fixed": "#d9e2ff",
        "inverse-on-surface": "#313030"
      },
      "fontFamily": {
        "headline": ["Noto Serif"],
        "body": ["Noto Serif"],
        "label": ["Inter"]
      }
    },
  },
  plugins: [],
}
